version: "3"

services:
  app:
    build:
      context: aplicacao/
      dockerfile: Dockerfile
    volumes:
      - ./aplicacao:/code
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    command: -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app_network

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
