version: "3"

services:
  postgres:
    image: postgres:13
    restart: always
    command: -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
